CREATE TABLE calendar_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  calendar_space_id BIGINT NOT NULL,
  organization_id BIGINT NULL,
  created_by BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NULL,
  location VARCHAR(200) NULL,
  start_time DATETIME(3) NOT NULL,
  end_time DATETIME(3) NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  all_day TINYINT(1) NOT NULL DEFAULT 0,
  visibility VARCHAR(32) NOT NULL DEFAULT 'space',
  source VARCHAR(32) NOT NULL DEFAULT 'manual',
  repeat_type VARCHAR(32) NOT NULL DEFAULT 'none',
  repeat_until DATETIME(3) NULL,
  repeat_count INT NULL,
  repeat_rule_text TEXT NULL,
  repeat_rule_json JSON NULL,
  project VARCHAR(128) NULL,
  owner_user_id BIGINT NULL,
  status VARCHAR(32) NULL,
  priority VARCHAR(32) NULL,
  tags JSON NULL,
  event_type VARCHAR(64) NULL,
  notes TEXT NULL,
  custom_fields JSON NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  INDEX idx_events_space_time (calendar_space_id, start_time, end_time),
  INDEX idx_events_created_by (created_by),
  INDEX idx_events_org_time (organization_id, start_time),
  INDEX idx_events_owner_user (owner_user_id),
  INDEX idx_events_project (calendar_space_id, project),
  INDEX idx_events_status (calendar_space_id, status),
  INDEX idx_events_priority (calendar_space_id, priority),
  CONSTRAINT fk_events_space FOREIGN KEY (calendar_space_id) REFERENCES calendar_spaces (id),
  CONSTRAINT fk_events_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
  CONSTRAINT fk_events_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_events_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id),
  CONSTRAINT ck_events_time_range CHECK (end_time > start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
