CREATE TABLE ai_tool_call_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  conversation_id BIGINT NOT NULL,
  message_id BIGINT NULL,
  user_id BIGINT NOT NULL,
  calendar_space_id BIGINT NOT NULL,
  tool_name VARCHAR(128) NOT NULL,
  risk_level VARCHAR(32) NOT NULL,
  required_permission VARCHAR(128) NULL,
  input_payload JSON NULL,
  output_payload JSON NULL,
  status VARCHAR(32) NOT NULL,
  error_code VARCHAR(64) NULL,
  error_message TEXT NULL,
  started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at DATETIME(3) NULL,
  INDEX idx_tool_logs_conversation_time (conversation_id, started_at),
  INDEX idx_tool_logs_user_time (user_id, started_at),
  INDEX idx_tool_logs_tool_name (tool_name),
  CONSTRAINT fk_tool_logs_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id),
  CONSTRAINT fk_tool_logs_message FOREIGN KEY (message_id) REFERENCES ai_messages (id),
  CONSTRAINT fk_tool_logs_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_tool_logs_space FOREIGN KEY (calendar_space_id) REFERENCES calendar_spaces (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE operation_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  calendar_space_id BIGINT NOT NULL,
  conversation_id BIGINT NULL,
  tool_call_id BIGINT NULL,
  operation_source VARCHAR(32) NOT NULL,
  operation_type VARCHAR(64) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id BIGINT NULL,
  before_snapshot JSON NULL,
  after_snapshot JSON NULL,
  undoable TINYINT(1) NOT NULL DEFAULT 0,
  undone TINYINT(1) NOT NULL DEFAULT 0,
  undo_expires_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_operation_user_time (user_id, created_at),
  INDEX idx_operation_space_time (calendar_space_id, created_at),
  INDEX idx_operation_undo (user_id, operation_source, undoable, undone, undo_expires_at),
  INDEX idx_operation_target (target_type, target_id),
  CONSTRAINT fk_operation_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_operation_space FOREIGN KEY (calendar_space_id) REFERENCES calendar_spaces (id),
  CONSTRAINT fk_operation_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id),
  CONSTRAINT fk_operation_tool_call FOREIGN KEY (tool_call_id) REFERENCES ai_tool_call_logs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
